### ISSUE TITLE
Wsb synth play does not work

### ISSUE THREAD

**Issue by vishalhify13** [drbergeron/wsb_synth_pub#13]
I use chrome and messege does not play. It collects in trash folder. I have iPhone. It work very well on desktop computer though.

**Comment by vishalhify13** [comment]
Even I installed Firefox on iPhone. Does not play.

**Comment by drbergeron** [comment]
Check the iphone accessibility features and make sure that you have a language installed. iphone is VERY finnicky with this because it doesn't tell you what you have installed, it just shows all of the possible things you can install. So you might have a voice selected that it can't play and it gives you zero feedback on it.

This site uses the HTML5 accessibility features to play the speech, which apple sucks at supporting because they want you to pony up money for theirs or something else dumb.

So follow the steps in the FAQ and see what happens, but you may need to experiment during market hours on the iphone to find the voice that's installed and available on the phone.

**Comment by vishalhify13** [comment]
I have downloaded language pack. Still no luck.
